[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
[project]
name = "Project5"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.11"',
]
[project.scripts]
Project5 = "Project5:main"  # call our function on startup